# Generated by Django 4.1.5 on 2023-01-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EGS', '0003_categorie_envie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='NCategorie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='EGS.categorie'),
            preserve_default=False,
        ),
    ]
