# Generated by Django 4.1.5 on 2023-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EGS', '0004_article_ncategorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
