# Generated by Django 4.1.5 on 2023-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EGS', '0005_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panier',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
