# Generated by Django 4.1.5 on 2023-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EGS', '0006_panier_email_panier_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
