# Generated by Django 4.1.5 on 2023-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EGS', '0007_article_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='prix_quantite',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
