# Generated by Django 4.1.5 on 2023-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EGS', '0010_remove_panier_prix_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='article',
            field=models.CharField(max_length=250),
        ),
    ]
