# Generated by Django 4.1.5 on 2023-01-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_deteste_post_post_dislikes_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='description',
        ),
    ]
