# Generated by Django 4.1.5 on 2023-01-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_commentaire_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=250)),
                ('Titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('images', models.ImageField(upload_to='poste')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='poste',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaire', to='Blog.poste'),
            preserve_default=False,
        ),
    ]
